# Assignment - Day 3

## Importing libraries

In [1]:
import numpy as np
import pandas as pd

### Task 1: Creating 2D matrix of shape (3,3)

In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

#### Multiplying every element by 2

In [4]:
arr2 = arr*2

#### print old and new arrays

In [8]:
print("old array: \n",arr)
print("\nnew array: \n", arr2)

old array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

new array: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Task 2: Create a Dataframe from a dictionary

In [11]:
dc = {"product_name": ["gold", "silver", "iron", "copper"],
      "price": [100000, 50000, 10000, 20000],
      "stock_quantity": [30, 80, 60, 40]}

df = pd.DataFrame(dc)

print(f"dataframe:\n{df}")

dataframe:
  product_name   price  stock_quantity
0         gold  100000              30
1       silver   50000              80
2         iron   10000              60
3       copper   20000              40


## Task 3: Data filtering operation on the DataFrame

In [12]:
filtered_df = df[df["stock_quantity"] > 50]
print(f"filtered DataFrame: \n{filtered_df}")

filtered DataFrame: 
  product_name  price  stock_quantity
1       silver  50000              80
2         iron  10000              60
